F/match results
AlexanderDefuria/FRC-Scouting pull request #111
Opened 2023-02-16 22:05 UTC by Vortex148

should upload data from match results to database. Should also calculate win/loss ratio

2023-02-16 23:23 UTC, AlexanderDefuria requested changes
Looks good overall!!

2023-02-16 23:23 UTC, AlexanderDefuria commented on apps/entry/views.py
>          # import_first()
Cleanup the comments

2023-02-16 23:23 UTC, AlexanderDefuria commented on apps/entry/views.py
>              "img":"NA"
Cleanup the whitespace

2023-02-16 23:23 UTC, AlexanderDefuria commented on apps/entry/imports.py
> +    for event in Event.objects.all():
This needs to be split up into smaller functions. Think about creating a method like
`get_match_data_event(event: Event)`  and then looping over the function call.

2023-02-16 23:23 UTC, AlexanderDefuria commented on apps/entry/imports.py
> +            for match in range(number_of_matches):
Try this like we did for the events.
```
base_data = make_request(...)
for match in base_data['Matches']:
   ...
```

2023-02-16 23:23 UTC, AlexanderDefuria commented on apps/entry/imports.py
> +                        # team_info.totalMatchesLost = 0
Cleanup the `#... = 0`

2023-02-16 23:23 UTC, AlexanderDefuria commented on apps/entry/imports.py
> +        try:
Is it possible to have this try statement surround less code?

2023-02-24 14:52 UTC, Vortex148 commented
Updated to separate events rather than all at once

2023-03-04 19:19 UTC, AlexanderDefuria approved these changes

2023-03-04 19:19 UTC, merged